[advisories]
db-path = "~/.cargo/advisory-db"
db-urls = ["https://github.com/rustsec/advisory-db"]
ignore = [
    { id = "RUSTSEC-2024-0437" },
    { id = "RUSTSEC-2025-0009" },
    { id = "RUSTSEC-2025-0010" },
    { id = "RUSTSEC-2025-0134" },
    { id = "RUSTSEC-2026-0037" },
    { id = "RUSTSEC-2026-0098" },
    { id = "RUSTSEC-2026-0099" },
    { id = "RUSTSEC-2026-0104" },
]

[bans]
multiple-versions = "warn"
wildcards = "allow"
highlight = "all"
skip = []

[licenses]
unlicensed = "deny"
allow = [
    "MIT",
    "Apache-2.0",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-3.0",
    "Unicode-DFS-2016",
    "Zlib",
    "0BSD",
    "MIT OR Apache-2.0",
    "MIT AND (MIT OR Apache-2.0)",
    "ISC AND MIT",
    "OpenSSL",
    "CC0-1.0",
    "BSL-1.0",
    "Unicode-3.0",
    "WTFPL",
]
copyleft = "warn"
confidence-threshold = 0.9

[sources]
unknown-registry = "deny"
unknown-git = "deny"
allow-registry = ["https://github.com/rust-lang/crates.io-index"]
allow-git = []
